name = "ai-trading-nexus"
compatibility_date = "2026-03-23"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "AGENTS_STATE"
id = "2b2de6ee3b204bb4a4a7b3586cdf66bb"
preview_id = "16e5d2f6abd343b8a07366b19e8e01de"

[[services]]
binding = "ENGINE_SERVICE"
service = "ai-trading-engine"
